Fixes a couple sorting bugs
facebooknuclide/nuclide-format-js pull request #75
Opened 2018-07-16 19:50 UTC by drmathochist

Destructured require fields should have capitalized entries first.
Requires should be sorted based on their raw module names, not aliases.

2018-07-16 21:45 UTC, hansonw commented
@xixixao i'm not familiar with the ESlint order-requires rules; does this seem consistent to you?

2018-07-17 13:56 UTC, xixixao requested changes
This PR should have a test that shows the change.

John you would need to run a codemod at FB with the new rules, and I'd guess this would cause a very large number of file changes. You'd also have to update our ESLint rule.

2018-07-17 14:25 UTC, drmathochist commented
I don't think I'd have to update the ESLint rule.  I'm offering these changes to bring this package in line with the ESLint rule.  I'm not sure what detail we can go into here, but I can reach out to you directly to show the reasoning for my two changes.

2018-07-17 16:42 UTC, drmathochist commented
I decided not to remove the `Immutable` alias, since testing shows that it's necessary for correct functioning of auto-imports.  As we discussed, the ESLint rule has been updated to not special-case this alias, and so it should be sorted according to its (lower-case) module name rather than its (upper-case) alias name.

2018-07-27 18:23 UTC, merged